name: "GradientBoosting"
scaler: "none"
params:
  _target_: sklearn.ensemble.GradientBoostingClassifier
  n_estimators: 200
  learning_rate: 0.1
  random_state: 42

search_space:
  n_estimators: [100, 200]
  learning_rate: [0.05, 0.1]
  max_depth: [3, 5]
